### ISSUE TITLE
Connection lost

### ISSUE THREAD

**Issue by tobias4910** [juancarloscp52/Entropy#3]
11:36:13.590
Encountered exception while handling in channel with name "entropy:join-confirm"
java.lang.IllegalArgumentException: Must specify name
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:122)
	at org.pircbotx.Configuration.<init>(Configuration.java:147)
	at org.pircbotx.Configuration$Builder.buildConfiguration(Configuration.java:894)
	at me.juancarloscp52.entropy.client.integrations.TwitchIntegrations.<init>(TwitchIntegrations.java:44)
	at me.juancarloscp52.entropy.client.ClientEventHandler.<init>(ClientEventHandler.java:36)
	at me.juancarloscp52.entropy.client.EntropyClient.lambda$onInitializeClient$0(EntropyClient.java:74)
	at me.juancarloscp52.entropy.client.EntropyClient$$Lambda$2422/1303329585.receive(Unknown Source)
	at net.fabricmc.fabric.impl.networking.client.ClientPlayNetworkAddon.receive(ClientPlayNetworkAddon.java:97)
	at net.fabricmc.fabric.impl.networking.client.ClientPlayNetworkAddon.receive(ClientPlayNetworkAddon.java:39)
	at net.fabricmc.fabric.impl.networking.AbstractChanneledNetworkAddon.handle(AbstractChanneledNetworkAddon.java:100)
	at net.fabricmc.fabric.impl.networking.client.ClientPlayNetworkAddon.handle(ClientPlayNetworkAddon.java:89)
	at net.minecraft.class_634.handler$zeo000$handleCustomPayload(class_634.java:2474)
	at net.minecraft.class_634.method_11152(class_634.java)
	at net.minecraft.class_2658.method_11457(class_2658.java:65)
	at net.minecraft.class_2658.method_11054(class_2658.java:10)
	at net.minecraft.class_2535.method_10759(class_2535.java:156)
	at net.minecraft.class_2535.method_10770(class_2535.java:147)
	at net.minecraft.class_2535.channelRead0(class_2535.java:52)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965)
	at io.netty.channel.local.LocalChannel.readInbound(LocalChannel.java:304)
	at io.netty.channel.local.LocalChannel.finishPeerRead0(LocalChannel.java:446)
	at io.netty.channel.local.LocalChannel.access$400(LocalChannel.java:51)
	at io.netty.channel.local.LocalChannel$5.run(LocalChannel.java:404)
	at io.netty.channel.DefaultEventLoop.run(DefaultEventLoop.java:54)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
	at java.lang.Thread.run(Thread.java:745)

**Comment by tobias4910** [comment]
this comes when i try to join a singleplayer world

**Comment by juancarloscp52** [comment]
looks like a problem parsing the twitch integration information. Please, try disabling twitch integration from the entropy settings menu and try to join a singleplayer world. If it works, probably there is a problem with the twitch credentials you've provided.

**Comment by tobias4910** [comment]
and how can i make the time until the next event longer than 45 seconds

**Comment by juancarloscp52** [comment]
for now the timer can only be set to 15, 30 and 45 seconds, but I might consider making it more customizable
